### ISSUE TITLE
Rename Syntax Language Name

### ISSUE THREAD

**Issue by Manuzor** [alexrp/st2-d#27]
Since the pretty-name of the syntax scheme for this package is simply `D`, just as the built-in version, I get the following:
![st3_dlang_checkedtwice](https://cloud.githubusercontent.com/assets/5539930/8504263/c4d35946-21ce-11e5-8394-53e76dc8a54a.png)
I am now also unable to set the "Open all with current extension as..." option to the version of this package, i.e. it will always use the old highlighting when I open any other *.d file.

I suppose something like `DLang` would be appropriate.

**Comment by sigod** [comment]
Hmm. It seams file should be renamed too.
